# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/205_brecci/give/slot_2 with storage zombies:bo3 weapons.w40.base
scoreboard players set @s active_weapon 1
