# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/haymaker12/give/slot_3 with storage zombies:bo3 weapons.w41.base
scoreboard players set @s active_weapon 2
