# Generated by blockbench/bo3_weapons/install_gameplay.py.
# Smart-slot assignment: first free slot, then active slot.
execute unless score @s gun_1 matches 1.. run return run function zbk:combat/weapons/guns/vesper/give/activate_1
execute unless score @s gun_2 matches 1.. run return run function zbk:combat/weapons/guns/vesper/give/activate_2
execute unless score @s gun_3 matches 1.. if score @s perk_mule matches 1.. run return run function zbk:combat/weapons/guns/vesper/give/activate_3
execute if score @s active_weapon matches 2 if score @s perk_mule matches 1.. run return run function zbk:combat/weapons/guns/vesper/give/activate_3
execute if score @s active_weapon matches 1 run return run function zbk:combat/weapons/guns/vesper/give/activate_2
function zbk:combat/weapons/guns/vesper/give/activate_1
