# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/man_o_war/give/slot_3 with storage zombies:bo3 weapons.w31.base
scoreboard players set @s active_weapon 2
