# Generated by tools/video_font/generate_video_font.js. Re-run the tool to update this file.
execute if score #de_intro_fr zbk_video matches 1700 run title @a title {"text":"\uEE48\uE0FF\uEE49","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1701 run title @a title {"text":"\uEE4A\uE0FF\uEE4B","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1702 run title @a title {"text":"\uEE4C\uE0FF\uEE4D","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1703 run title @a title {"text":"\uEE4E\uE0FF\uEE4F","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1704 run title @a title {"text":"\uEE50\uE0FF\uEE51","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1705 run title @a title {"text":"\uEE52\uE0FF\uEE53","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1706 run title @a title {"text":"\uEE54\uE0FF\uEE55","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1707 run title @a title {"text":"\uEE56\uE0FF\uEE57","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1708 run title @a title {"text":"\uEE58\uE0FF\uEE59","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1709 run title @a title {"text":"\uEE5A\uE0FF\uEE5B","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1710 run title @a title {"text":"\uEE5C\uE0FF\uEE5D","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1711 run title @a title {"text":"\uEE5E\uE0FF\uEE5F","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1712 run title @a title {"text":"\uEE60\uE0FF\uEE61","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1713 run title @a title {"text":"\uEE62\uE0FF\uEE63","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1714 run title @a title {"text":"\uEE64\uE0FF\uEE65","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
execute if score #de_intro_fr zbk_video matches 1715 run title @a title {"text":"\uEE66\uE0FF\uEE67","font":"zbk_der_eisendrache:intro_cutscene/video","color":"white","shadow_color":[0,0,0,0]}
