# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/bo3/registry/select_4
function zombies:combat/weapons/guns/bo3/reload/shell with storage zombies:bo3 profile
