# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/bo3/registry/select_2
function zombies:combat/weapons/guns/bo3/reload/start with storage zombies:bo3 profile
