# Generated by blockbench/bo3_weapons/install_gameplay.py.
scoreboard players operation #gun_id temp = @s gun_3
function zombies:combat/weapons/guns/bo3/migration/id
execute if score #gun_id temp = @s gun_3 run return 0
scoreboard players operation @s gun_3 = #gun_id temp
function zombies:combat/weapons/guns/bo3/registry/select_3
function zombies:combat/weapons/guns/bo3/inventory/capacity with storage zombies:bo3 profile
scoreboard players set @s bo3_burst_3 0
scoreboard players set @s bo3_delay_3 0
scoreboard players set @s shots_3 0
scoreboard players set @s fire_3 0
scoreboard players set @s is_reloading_3 0
scoreboard players set @s reload_timer_3 0
