# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zbk:combat/weapons/guns/bo3/registry/select_4
execute if score @s gun_4 matches 39 if score @s bo3_press matches 1 if score @s ammo_4 matches 1.. if score @s is_reloading_4 matches 1 run function zbk:combat/weapons/reload_audio/stop {slug:"krm262",slot:4}
execute if score @s gun_4 matches 39 if score @s bo3_press matches 1 if score @s ammo_4 matches 1.. run scoreboard players set @s is_reloading_4 0
scoreboard players set @s bo3_budget 0
function zbk:combat/weapons/guns/bo3/input/pump with storage zbk:bo3 profile
