# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/bo3/registry/select_1
execute if score @s gun_1 matches 39 if score @s bo3_press matches 1 if score @s ammo_1 matches 1.. if score @s is_reloading_1 matches 1 run function zombies:combat/weapons/reload_audio/stop {slug:"krm262",slot:1}
execute if score @s gun_1 matches 39 if score @s bo3_press matches 1 if score @s ammo_1 matches 1.. run scoreboard players set @s is_reloading_1 0
scoreboard players set @s bo3_budget 0
function zombies:combat/weapons/guns/bo3/input/pump with storage zombies:bo3 profile
