# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/guns/bo3/registry/select_3
execute if score @s gun_3 matches 39 if score @s bo3_press matches 1 if score @s ammo_3 matches 1.. if score @s is_reloading_3 matches 1 run function zombies:combat/weapons/reload_audio/stop {slug:"krm262",slot:3}
execute if score @s gun_3 matches 39 if score @s bo3_press matches 1 if score @s ammo_3 matches 1.. run scoreboard players set @s is_reloading_3 0
scoreboard players set @s bo3_budget 0
function zombies:combat/weapons/guns/bo3/input/pump with storage zombies:bo3 profile
