# Generated by blockbench/bo3_weapons/install_gameplay.py.
function zombies:combat/weapons/reload_audio/stop_slot {slot:3}
$scoreboard players set @s gun_3 $(id)
$scoreboard players set @s max_ammo_3 $(max_ammo)
$scoreboard players set @s max_reserve_3 $(max_reserve)
scoreboard players operation @s ammo_3 = @s max_ammo_3
scoreboard players operation @s reserve_ammo_3 = @s max_reserve_3
scoreboard players set @s shots_3 0
scoreboard players set @s fire_3 0
scoreboard players set @s cooldown_3 0
scoreboard players set @s is_reloading_3 0
scoreboard players set @s reload_timer_3 0
scoreboard players set @s tier_3 0
scoreboard players set @s element_3 0

scoreboard players set @s bo3_delay_3 0
scoreboard players set @s bo3_burst_3 0
function zombies:combat/weapons/guns/bo3/input/cancel
