# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '78ad1b8062d03b43e471eec25f88e45bd68a8042a16153a9f84148224a17e4df'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack