# Generated by tools/video_font/generate_video_font.js. Re-run the tool to update this file.
scoreboard objectives add zbk_video dummy
scoreboard players set #de_intro_on zbk_video 0
schedule clear zbk_der_eisendrache:intro_cutscene/video/tick
stopwatch remove zbk_der_eisendrache:intro_cutscene/video
stopsound @a master zbk_der_eisendrache:maps.der_eisendrache.intro_cutscene.video
title @a clear
title @a times 10 70 20
