# Generated by tools/video_font/generate_video_font.js. Re-run the tool to update this file.
execute unless score #active zbk.de matches 1 run return run function zbk_der_eisendrache:intro_cutscene/video/stop
scoreboard objectives add zbk_video dummy
scoreboard players set #de_intro_fr zbk_video 0
scoreboard players set #de_intro_on zbk_video 1
title @a times 0 999999 0
stopsound @a master zbk_der_eisendrache:maps.der_eisendrache.intro_cutscene.video
stopwatch create zbk_der_eisendrache:intro_cutscene/video
stopwatch restart zbk_der_eisendrache:intro_cutscene/video
execute as @a at @s run playsound zbk_der_eisendrache:maps.der_eisendrache.intro_cutscene.video master @s ~ ~ ~ 1 1
function zbk_der_eisendrache:intro_cutscene/video/show
schedule function zbk_der_eisendrache:intro_cutscene/video/tick 1t replace
