# Generated by tools/video_font/generate_video_font.js. Re-run the tool to update this file.
execute unless score #de_intro_on zbk_video matches 1 run return 0
execute unless score #active zbk.de matches 1 run return run function zbk_der_eisendrache:intro_cutscene/video/stop
scoreboard players operation #de_intro_prev zbk_video = #de_intro_fr zbk_video
execute store result score #de_intro_fr zbk_video run stopwatch query zbk_der_eisendrache:intro_cutscene/video 20
execute if score #de_intro_fr zbk_video matches 1716.. run return run function zbk_der_eisendrache:intro_cutscene/video/finish
execute unless score #de_intro_fr zbk_video = #de_intro_prev zbk_video run function zbk_der_eisendrache:intro_cutscene/video/show
schedule function zbk_der_eisendrache:intro_cutscene/video/tick 1t replace
