# Generated by blockbench/bo3_weapons/install_gameplay.py.
execute if score #gun_id temp matches 1 run scoreboard players set #gun_id temp 42
execute if score #gun_id temp matches 2 run scoreboard players set #gun_id temp 25
execute if score #gun_id temp matches 3 run scoreboard players set #gun_id temp 46
execute if score #gun_id temp matches 4 run scoreboard players set #gun_id temp 34
execute if score #gun_id temp matches 5 run scoreboard players set #gun_id temp 20
execute if score #gun_id temp matches 6 run scoreboard players set #gun_id temp 30
execute if score #gun_id temp matches 8 run scoreboard players set #gun_id temp 33
execute if score #gun_id temp matches 9 run scoreboard players set #gun_id temp 39
execute if score #gun_id temp matches 10 run scoreboard players set #gun_id temp 44
