# Generated by blockbench/bo3_weapons/install_gameplay.py.
scoreboard players operation #gun_id temp = @s gun_2
function zbk:combat/weapons/guns/bo3/migration/id
execute if score #gun_id temp = @s gun_2 run return 0
scoreboard players operation @s gun_2 = #gun_id temp
function zbk:combat/weapons/guns/bo3/registry/select_2
function zbk:combat/weapons/guns/bo3/inventory/capacity with storage zbk:bo3 profile
scoreboard players set @s bo3_burst_2 0
scoreboard players set @s bo3_delay_2 0
scoreboard players set @s shots_2 0
scoreboard players set @s fire_2 0
scoreboard players set @s is_reloading_2 0
scoreboard players set @s reload_timer_2 0
