# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_back_tank) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.75f,0f,0f,-1f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chest) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.8125f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.375f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_claw_arm) {transformation: [-1f,0f,0f,0.9375f,0f,1f,0f,0.9375f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_shoulder) {transformation: [-1f,0f,0f,0.625f,0f,1f,0f,1.8125f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_flamethrower) {transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,0.625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flamethrower_tube) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,1.375f,0f,0f,-1f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1f,0f,0f,-0.8125f,0f,1f,0f,0.75f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_shoulder) {transformation: [-1f,0f,0f,-0.625f,0f,1f,0f,1.8125f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hip_mount) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.125f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_upper_leg) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_lower_leg) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.5625f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.1875f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_upper_leg) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,1f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_lower_leg) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.5625f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.1875f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}