# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.back_tank] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_back_tank set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.chest] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.left_claw_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_claw_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.left_shoulder] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_shoulder set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_flamethrower] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_flamethrower set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.flamethrower_tube] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_flamethrower_tube set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_shoulder] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_shoulder set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.hip_mount] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hip_mount set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.left_upper_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_upper_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.left_lower_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_lower_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.left_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_foot set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_upper_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_upper_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_lower_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_lower_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.de_panzer.node.right_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_foot set from storage animated_java:gu out