# Generated by tools/generate_de_panzer_minecraft_export.js for the current de_panzer blueprint.
$data merge entity $(bone_torso) {transformation:[0.9028f,0f,0f,0f,0f,0.9028f,0f,1.3542f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_back_tank) {transformation:[0.9028f,0f,0f,0f,0f,0.9028f,0f,1.5799f,0f,0f,0.9028f,0.5078f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_chest) {transformation:[0.9028f,0f,0f,0f,0f,0.9028f,0f,1.6363f,0f,0f,0.9028f,0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_head) {transformation:[0.9028f,0f,0f,0f,0f,0.9028f,0f,2.1442f,0f,0f,0.9028f,0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_shoulder) {transformation:[0.9028f,0f,0f,-0.5642f,0f,0.9028f,0f,1.6363f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_claw_arm) {transformation:[0.9028f,0f,0f,-0.8464f,0f,0.9028f,0f,0.8464f,0f,0f,0.9028f,0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_shoulder) {transformation:[0.9028f,0f,0f,0.5643f,0f,0.9028f,0f,1.6363f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_hand) {transformation:[0.9028f,0f,0f,0.7335f,0f,0.9028f,0f,0.6771f,0f,0f,0.9028f,-0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_flamethrower) {transformation:[0.9028f,0f,0f,0.9592f,0f,0.9028f,0f,0.5643f,0f,0f,0.9028f,0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_flamethrower_tube) {transformation:[0.9028f,0f,0f,0.6771f,0f,0.9028f,0f,1.2414f,0f,0f,0.9028f,0.3386f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_hip_mount) {transformation:[0.9028f,0f,0f,0f,0f,0.9028f,0f,1.0157f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_upper_leg) {transformation:[0.9028f,0f,0f,-0.2257f,0f,0.9028f,0f,0.9028f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_lower_leg) {transformation:[0.9028f,0f,0f,-0.2257f,0f,0.9028f,0f,0.5078f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_foot) {transformation:[0.9028f,0f,0f,-0.2257f,0f,0.9028f,0f,0.1693f,0f,0f,0.9028f,-0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_upper_leg) {transformation:[0.9028f,0f,0f,0.2257f,0f,0.9028f,0f,0.9028f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_lower_leg) {transformation:[0.9028f,0f,0f,0.2257f,0f,0.9028f,0f,0.5078f,0f,0f,0.9028f,0.1129f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_foot) {transformation:[0.9028f,0f,0f,0.2257f,0f,0.9028f,0f,0.1693f,0f,0f,0.9028f,-0.0564f,0f,0f,0f,1f],start_interpolation:0,interpolation_duration:1}
